---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ww-gitops
  namespace: kube-system
spec:
  interval: 1m0s
  url: https://aws.github.io/eks-charts
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nginx-gitops
  namespace: kube-system
spec:
  interval: 10m0s
  url: https://charts.bitnami.com/bitnami/
