---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    flux.weave.works/automated: "true"
    # flux.weave.works/ignore: "true"
    # flux.weave.works/tag.nginx: semver:~1.16
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/locked_user: User Name <user@example.com>
spec:
  releaseName: aws-load-balancer-controller
  chart:
    repository: https://aws.github.io/eks-charts/
    name: aws-load-balancer-controller
    version: 1.4.4
  values:
    clusterName: ekscluster2
    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      name: aws-load-balancer-controller

