---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  chart:
    spec:
      chart: aws-load-balancer-controller
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
      version: 1.4.4
  values:
    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      name: aws-load-balancer-controller
  interval: 1m0s
  valuesFrom:
  - kind: ConfigMap
    name: aws-lbc-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity

