---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ms-gitops
      version: 3.8.3
  values:
    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      name: metrics-server
  interval: 1m0s

