---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mywebserver
  namespace: nginx
spec:
  releaseName: mywebserver
  chart:
    spec:
      chart: nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: nginx-gitops
      version: 11.1.5
  values:
    usePassword: true
    image:
      registry: public.ecr.aws
      repository: bitnami/nginx
      tag: 1.21.6
    service:
      type: LoadBalancer
      port: 80
      nodePorts:
        http: ""
      externalTrafficPolicy: Cluster
    ingress:
      enabled: false
    metrics:
      enabled: false
  interval: 1m0s

