apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: eks-example
  name: eks-example
  annotations:
    # Container Image Automated Updates
    flux.weave.works/automated: "true"
    # do not apply this manifest on the cluster
    flux.weave.works/ignore: "true"

